export const OTP_SENT_INIT = "OTP_SENT_INIT";
export const OTP_SENT_SUCCESS = "OTP_SENT_SUCCESS";
export const OTP_SENT_FAIL = "OTP_SENT_FAIL";

export const AUTH_LOGIN_INIT = "AUTH_LOGIN_INIT";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const OTP_VERIFY_INIT = "OTP_VERIFY_INIT";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const OTP_VERIFY_FAIL = "OTP_VERIFY_FAIL";

export const AUTH_SIGNUP_INIT = "AUTH_SIGNUP_INIT";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL";

export const AUTH_PROFILE_INIT = "AUTH_PROFILE_INIT";
export const AUTH_PROFILE_SUCCESS = "AUTH_PROFILE_SUCCESS";
export const AUTH_PROFILE_FAIL = "AUTH_PROFILE_FAIL";

export const GET_FUND_INIT = "GET_FUND_INIT";
export const GET_FUND_SUCCESS = "GET_FUND_SUCCESS";
export const GET_FUND_FAIL = "GET_FUND_FAIL";

export const AUTH_PROFILE_UPDATE_SUCCESS = "AUTH_PROFILE_UPDATE_SUCCESS";
export const AUTH_PROFILE_UPDATE_FAIL = "AUTH_PROFILE_UPDATE_FAIL";

export const ZEBULL_BROKER_INIT = "ZEBULL_BROKER_INIT";
export const ZEBULL_BROKER_SUCCESS = " ZEBULL_BROKER_SUCCESS";
export const ZEBULL_BROKER_FAIL = " ZEBULL_BROKER_FAIL";

export const ICICI_BROKER_INIT = "ICICI_BROKER_INIT";
export const ICICI_BROKER_SUCCESS = " ICICI_BROKER_SUCCESS";
export const ICICI_BROKER_FAIL = " ICICI_BROKER_FAIL";

export const ANGEL_BROKER_INIT = "ANGEL_BROKER_INIT";
export const ANGEL_BROKER_SUCCESS = " ANGEL_BROKER_SUCCESS";
export const ANGEL_BROKER_FAIL = " ANGEL_BROKER_FAIL";

export const ZERODHA_BROKER_INIT = "ZERODHA_BROKER_INIT";
export const ZERODHA_BROKER_SUCCESS = " ZERODHA_BROKER_SUCCESS";
export const ZERODHA_BROKER_FAIL = " ZERODHA_BROKER_FAIL";

export const FINVASIA_BROKER_INIT = "FINVASIA_BROKER_INIT";
export const FINVASIA_BROKER_SUCCESS = " FINVASIA_BROKER_SUCCESS";
export const FINVASIA_BROKER_FAIL = " FINVASIA_BROKER_FAIL";

export const KOTAK_BROKER_INIT = "KOTAK_BROKER_INIT";
export const KOTAK_BROKER_SUCCESS = " KOTAK_BROKER_SUCCESS";
export const KOTAK_BROKER_FAIL = " KOTAK_BROKER_FAIL";

export const ALICE_BROKER_INIT = "ALICE_BROKER_INIT";
export const ALICE_BROKER_SUCCESS = " ALICE_BROKER_SUCCESS";
export const ALICE_BROKER_FAIL = " ALICE_BROKER_FAIL";

export const FYERS_BROKER_INIT = "FYERS_BROKER_INIT";
export const FYERS_BROKER_SUCCESS = " FYERS_BROKER_SUCCESS";
export const FYERS_BROKER_FAIL = " FYERS_BROKER_FAIL";

export const SHAREKHAN_BROKER_INIT = "SHAREKHAN_BROKER_INIT";
export const SHAREKHAN_BROKER_SUCCESS = "SHAREKHAN_BROKER_SUCCESS";
export const SHAREKHAN_BROKER_FAIL = "SHAREKHAN_BROKER_FAIL";

export const BROKER_STATUS_INIT = "BROKER_STATUS_INIT";
export const BROKER_STATUS_SUCCESS = "BROKER_STATUS_SUCCESS";
export const BROKER_STATUS_FAIL = "BROKER_STATUS_FAIL";

export const PAPER_PROFIT_DETAILS_INIT = "PAPER_PROFIT_DETAILS_INIT";
export const PAPER_PROFIT_DETAILS_SUCCESS = "PAPER_PROFIT_DETAILS_SUCCESS";
export const PAPER_PROFIT_DETAILS_FAIL = "PAPER_PROFIT_DETAILS_FAIL";

export const CREATE_STRATEGY_INIT = "CREATE_STRATEGY_INIT";
export const CREATE_STRATEGY_SUCCESS = "CREATE_STRATEGY_SUCCESS";
export const CREATE_STRATEGY_FAIL = "CREATE_STRATEGY_FAIL";

export const PROFIT_DETAILS_INIT = "PROFIT_DETAILS_INIT";
export const PROFIT_DETAILS_SUCCESS = "PROFIT_DETAILS_SUCCESS";
export const PROFIT_DETAILS_FAIL = "PROFIT_DETAILS_FAIL";

export const PAPER_ORDER_DETAILS_INIT = "PAPER_ORDER_DETAILS_INIT";
export const PAPER_ORDER_DETAILS_SUCCESS = "PAPER_ORDER_DETAILS_SUCCESS";
export const PAPER_ORDER_DETAILS_FAIL = "PAPER_ORDER_DETAILS_FAIL";

export const LIVE_ORDER_DETAILS_INIT = "LIVE_ORDER_DETAILS_INIT";
export const LIVE_ORDER_DETAILS_SUCCESS = "LIVE_ORDER_DETAILS_SUCCESS";
export const LIVE_ORDER_DETAILS_FAIL = "LIVE_ORDER_DETAILS_FAIL";

export const SIGNAL_DETAILS_INIT = "SIGNAL_DETAILS_INIT";
export const SIGNAL_DETAILS_SUCCESS = "SIGNAL_DETAILS_SUCCESS";
export const SIGNAL_DETAILS_FAIL = "SIGNAL_DETAILS_FAIL";

export const LIVE_FEED_DATA_SUCCESS = "LIVE_FEED_DAT_SUCCESS";
export const GET_OVERALL_PROFIT_LOSS_SUCCESS =
  "GET_OVERALL_PROFIT_LOSS_SUCCESS";

export const ADMIN_LIVE_POSITION_INIT = "ADMIN_LIVE_POSITION_INIT";
export const ADMIN_LIVE_POSITION_SUCCESS = "ADMIN_LIVE_POSITION_SUCCESS";
export const ADMIN_LIVE_POSITION_FAIL = "ADMIN_LIVE_POSITION_FAIL";

export const ADMIN_PAPER_POSITION_INIT = "ADMIN_PAPER_POSITION_INIT";
export const ADMIN_PAPER_POSITION_SUCCESS = "ADMIN_PAPER_POSITION_SUCCESS";
export const ADMIN_PAPER_POSITION_FAIL = "ADMIN_PAPER_POSITION_FAIL";

export const GET_ADMIN_PAPER_ORDER_SUCCESS = "GET_ADMIN_PAPER_ORDER_SUCCESS";
export const GET_ADMIN_LIVE_ORDER_SUCCESS = "GET_ADMIN_LIVE_ORDER_SUCCESS";
export const GET_ADMIN_PAPER_ORDER_FAIL = "GET_ADMIN_PAPER_ORDER_FAIL";
export const GET_ADMIN_LIVE_ORDER_FAIL = "GET_ADMIN_LIVE_ORDER_FAIL";

export const GET_TODAY_DASHBOARD_COUNT_INIT = "GET_TODAY_DASHBOARD_COUNT_INIT";
export const GET_TODAY_DASHBOARD_COUNT_SUCCESS =
  "GET_TODAY_DASHBOARD_COUNT_SUCCESS";
export const GET_TODAY_DASHBOARD_COUNT_FAIL = "GET_TODAY_DASHBOARD_COUNT_FAIL";

export const GET_DASHBOARD_COUNT_INIT = "GET_DASHBOARD_COUNT_INIT";
export const GET_DASHBOARD_COUNT_SUCCESS = "GET_DASHBOARD_COUNT_SUCCESS";
export const GET_DASHBOARD_COUNT_FAIL = "GET_DASHBOARD_COUNT_FAIL";

export const GET_ADMIN_PL_REPORT_SUCCESS = "GET_ADMIN_PL_REPORT_SUCCESS";
export const GET_ADMIN_PL_REPORT_FAIL = "GET_ADMIN_PL_REPORT_FAIL";

export const GET_ADMIN_PL_PAPER_REPORT_SUCCESS =
  "GET_ADMIN_PL_PAPER_REPORT_SUCCESS";
export const GET_ADMIN_PL_PAPER_REPORT_FAIL = "GET_ADMIN_PL_PAPER_REPORT_FAIL";

export const GET_ALERT_ADMIN_SUCCESS = "GET_ALERT_ADMIN_SUCCESS";
export const GET_ALERT_ADMIN_FAIL = "GET_ALERT_ADMIN_FAIL";
export const GET_ALERT_INIT = "GET_ALERT_INIT";

export const SEND_ALERT_ADMIN_SUCCESS = "SEND_ALERT_ADMIN_SUCCESS";
export const SEND_ALERT_ADMIN_FAIL = "SEND_ALERT_ADMIN_FAIL";
export const UPDATE_ALERT_SUCCESS = "UPDATE_ALERT_SUCCESS";
export const UPDATE_ALERT_FAIL = "UPDATE_ALERT_FAIL";
export const DELETE_ALERT_SUCCESS = "DELETE_ALERT_SUCCESS";
export const DELETE_ALERT_FAIL = "DELETE_ALERT_FAIL";
export const GET_SEGMENT_SYMBOL_ALERT_SUCCESS =
  "GET_SEGMENT_SYMBOL_ALERT_SUCCESS";
export const GET_SEGMENT_SYMBOL_ALERT_FAIL = "GET_SEGMENT_SYMBOL_ALERT_FAIL";
export const DELETE_BULK_ALERT_SUCCESS = "DELETE_BULK_ALERT_SUCCESS";
export const DELETE_BULK_ALERT_FAIL = "DELETE_BULK_ALERT_FAIL";
export const UPLOAD_BULK_ALERT_SUCCESS = "UPLOAD_BULK_ALERT_SUCCESS";
export const UPLOAD_BULK_ALERT_FAIL = "UPLOAD_BULK_ALERT_FAIL";
export const FUTURE_ALERT_DATA_SUCCESS = "FUTURE_ALERT_DATA_SUCCESS";
export const FUTURE_ALERT_DATA_FAIL = "FUTURE_ALERT_DATA_FAIL";
export const OPTION_ALERT_DATA_SUCCESS = "OPTION_ALERT_DATA_SUCCESS";
export const OPTION_ALERT_DATA_FAIL = "OPTION_ALERT_DATA_FAIL";
export const OPTION_STRIKE_DATA_SUCCESS = "OPTION_STRIKE_DATA_SUCCESS";
export const OPTION_STRIKE_DATA_FAIL = "OPTION_STRIKE_DATA_FAIL";
export const GET_ALERT_PRICE_SUCCESS = "GET_ALERT_PRICE_SUCCESS";
export const GET_ALERT_PRICE_FAIL = "GET_ALERT_PRICE_FAIL";

export const GET_INDICATORS_SUCCESS = "GET_INDICATORS_SUCCESS";
export const GET_INDICATORS_FAIL = "GET_INDICATORS_FAIL";
export const GET_SINGLE_INDICATORS_SUCCESS = "GET_SINGLE_INDICATORS_SUCCESS";
export const GET_SINGLE_INDICATORS_FAIL = "GET_SINGLE_INDICATORS_FAIL";

export const GET_WATCH_LIST_DATA_INIT = "GET_WATCH_LIST_DATA_INIT";
export const GET_WATCH_LIST_DATA_SUCCESS = "GET_WATCH_LIST_DATA_SUCCESS";
export const GET_WATCH_LIST_DATA_FAIL = "GET_WATCH_LIST_DATA_FAIL";
export const ADD_WATCH_LIST_SUCCESS = "ADD_WATCH_LIST_SUCCESS";
export const ADD_WATCH_LIST_FAIL = "ADD_WATCH_LIST_FAIL";
export const GET_WATCH_LIST_LIVE_DATA_SUCCESS =
  "GET_WATCH_LIST_LIVE_DATA_SUCCESS";
export const GET_WATCH_LIST_LIVE_DATA_FAIL = "GET_WATCH_LIST_LIVE_DATA_FAIL";
export const DELETE_WATCH_LIST_DATA_SUCCESS = "DELETE_WATCH_LIST_DATA_SUCCESS";
export const DELETE_WATCH_LIST_DATA_FAIL = "DELETE_WATCH_LIST_DATA_FAIL";

export const GET_LIVE_POSITION_SUCCESS = "GET_LIVE_POSITION_SUCCESS";
export const CREATE_POSITION_SUCCESS = "CREATE_POSITION_SUCCESS";
export const CREATE_POSITION_FAIL = "CREATE_POSITION_FAIL";
export const SQUARE_OFF_LIVE_POSITION_SUCCESS =
  "SQUARE_OFF_LIVE_POSITION_SUCCESS";
export const SQUARE_OFF_LIVE_POSITION_FAIL = "SQUARE_OFF_LIVE_POSITION_FAIL";
export const SQUARE_OFF_ALL_LIVE_POPSITION_SUCCESS =
  "SQUARE_OFF_ALL_LIVE_POPSITION_SUCCESS";
export const SQUARE_OFF_ALL_LIVE_POPSITION_FAIL =
  "SQUARE_OFF_ALL_LIVE_POPSITION_FAIL";

export const GET_LIVE_TRADE_DETAILS_SUCCESS = "GET_LIVE_TRADE_DETAILS_SUCCESS";
export const GET_LIVE_TRADE_DETAILS_FAIL = "GET_LIVE_TRADE_DETAILS_FAIL";

export const POST_ATH_INIT = "POST_ATH_INIT";
export const POST_ATH_SUCCESS = "POST_ATH_SUCCESS";
export const POST_ATH_FAIL = "POST_ATH_FAIL";

export const POST_ATHORDER_INIT = "POST_ATHORDER_INIT";
export const POST_ATHORDER_SUCCESS = "POST_ATHORDER_SUCCESS";
export const POST_ATHORDER_FAIL = "POST_ATHORDER_FAIL";

export const POST_POSITION_CLOSEL_INIT = "POST_POSITION_CLOSEL_INIT";
export const POST_POSITION_CLOSEL_SUCCESS = "POST_POSITION_CLOSEL_SUCCESS";
export const POST_POSITION_CLOSEL_FAIL = "POST_POSITION_CLOSEL_FAIL";

export const POST_POSITION_MODIFY_ORDER_INIT =
  "POST_POSITION_MODIFY_ORDER_INIT";
export const POST_POSITION_MODIFY_ORDER_SUCCESS =
  "POST_POSITION_MODIFY_ORDER_SUCCESS";
export const POST_POSITION_MODIFY_ORDER_FAIL =
  "POST_POSITION_MODIFY_ORDER_FAIL";

export const POST_POSITION_CANCEL_ORDER_INIT =
  "POST_POSITION_CANCEL_ORDER_INIT";
export const POST_POSITION_CANCEL_ORDER_SUCCESS =
  "POST_POSITION_CANCEL_ORDER_SUCCESS";
export const POST_POSITION_CANCEL_ORDER_FAIL =
  "POST_POSITION_CANCEL_ORDER_FAIL";

export const POST_ATH_ADDPORTFOLIO_INIT = "POST_ATH_ADDPORTFOLIO_INIT";
export const POST_ATH_ADDPORTFOLIO_SUCCESS = "POST_ATH_ADDPORTFOLIO_SUCCESS";
export const POST_ATH_ADDPORTFOLIO_FAIL = "POST_ATH_ADDPORTFOLIO_FAIL";

export const GET_ATH_PORTFOLIO_INIT = "GET_ATH_PORTFOLIO_INIT";
export const GET_ATH_PORTFOLIO_SUCCESS = "GET_ATH_PORTFOLIO_SUCCESS";
export const GET_ATH_PORTFOLIO_FAIL = "GET_ATH_PORTFOLIO_FAIL";

export const ADMIN_PAPER_ORDER_INIT = "ADMIN_PAPER_ORDER_INIT";
export const ADMIN_PAPER_ORDER_SUCCESS = "ADMIN_PAPER_ORDER_SUCCESS";
export const ADMIN_PAPER_ORDER_FAIL = "ADMIN_PAPER_ORDER_FAIL";

export const GET_INDICATORS_DATA_SOCKET_SUCCESS =
  "GET_INDICATORS_DATA_SOCKET_SUCCESS";

export const GET_PORTOFOLIO_INDICATORS_DATA_SOCKET_SUCCESS =
  "GET_PORTOFOLIO_INDICATORS_DATA_SOCKET_SUCCESS";

export const ADD_PORTFOLIO_DATA_SUCCESS = "ADD_PORTFOLIO_DATA_SUCCESS";
export const ADD_PORTFOLIO_DATA_FAIL = "ADD_PORTFOLIO_DATA_FAIL";

export const REMOVE_PORTFOLIO_DATA_SUCCESS = "REMOVE_PORTFOLIO_DATA_SUCCESS";
export const REMOVE_PORTFOLIO_DATA_FAIL = "REMOVE_PORTFOLIO_DATA_FAIL";

export const GET_STRATEGY_DATA_SUCCESS = "GET_STRATEGY_DATA_SUCCESS";
export const GET_STRATEGY_DATA_FAIL = "GET_STRATEGY_DATA_FAIL";

export const POST_USER_STRATEGY_DATA_SUCCESS =
  "POST_USER_STRATEGY_DATA_SUCCESS";
export const POST_USER_STRATEGY_DATA_FAIL = "POST_USER_STRATEGY_DATA_FAIL";

export const GET_USER_STRATEGY_DETAILS_SUCCESS =
  "GET_USER_STRATEGY_DETAILS_SUCCESS";
export const GET_USER_STRATEGY_DETAILS_FAIL = "GET_USER_STRATEGY_DETAILS_FAIL";

export const DELETE_USER_STRATEGY_DATA_SUCCESS =
  "DELETE_USER_STRATEGY_DATA_SUCCESS";
export const DELETE_USER_STRATEGY_DATA_FAIL = "DELETE_USER_STRATEGY_DATA_FAIL";

export const GET_STRATEGY_CODE_SUCCESS = "GET_STRATEGY_CODE_SUCCESS";
export const GET_STRATEGY_CODE_FAIL = "GET_STRATEGY_CODE_FAIL";

export const GET_BANKNIFTY_DETAILS_SUCCESS = "GET_BANKNIFTY_DETAILS_SUCCESS";
export const GET_BANKNIFTY_DETAILS_FAIL = "GET_BANKNIFTY_DETAILS_FAIL";

export const GET_USER_BANKNIFTY_SUCCESS = "GET_USER_BANKNIFTY_SUCCESS";
export const GET_USER_BANKNIFTY_FAIL = "GET_USER_BANKNIFTY_FAIL";

export const ADD_USER_BANKNIFTY_SUCCESS = "ADD_USER_BANKNIFTY_SUCCESS";
export const ADD_USER_BANKNIFTY_FAIL = "ADD_USER_BANKNIFTY_FAIL";

export const OPEN_CONFIRM_DIALOG = "OPEN_CONFIRM_DIALOG";
export const CLOSE_CONFIRM_DIALOG = "CLOSE_CONFIRM_DIALOG";
export const SET_CONFRIM = "SET_CONFIRM";
export const SET_INTIAL_STATE = "SET_INTIAL_STATE";
